## Упражнения по библиотеке Numpy

In [86]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [87]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.array(data)

print(arr)

for item in range(len(arr)):
    if 3 < item < 8:
        arr[item] = -item

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4 -4 -5 -6 -7  9 10]


**2.** Заменить максимальный элемент случайного массива на 0

In [88]:
max_value = max(arr)
idx = np.where(arr == max_value)
arr[idx] = 0
print(arr)

[ 1  2  3  4 -4 -5 -6 -7  9  0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [89]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5])))

[[1 4]
 [1 5]
 [2 4]
 [2 5]
 [3 4]
 [3 5]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [90]:
A = np.random.randint(0,5,(8,3))
print(A)
B = np.random.randint(0,5,(2,2))
print(B)

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1, 2, 3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[3 3 3]
 [2 0 3]
 [0 2 0]
 [4 4 4]
 [2 4 4]
 [3 2 1]
 [3 0 1]
 [3 2 0]]
[[0 1]
 [1 4]]
[2 3 4 5 6]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [91]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 4 2]
 [2 2 0]
 [1 4 4]
 [4 3 3]
 [1 0 1]
 [2 4 1]
 [2 4 0]
 [3 1 4]
 [1 2 1]
 [1 4 4]]
[[4 4 2]
 [2 2 0]
 [1 4 4]
 [4 3 3]
 [1 0 1]
 [2 4 1]
 [2 4 0]
 [3 1 4]
 [1 2 1]
 [1 4 4]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [92]:
Z = np.random.randint(0, 2, (6,3))
print(Z)
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [1 1 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 0]]
[[0 0 0]
 [1 0 0]
 [1 1 0]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [93]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
np.prod(np.diag(X)[np.diag(X)!=0])

3

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [94]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
sorted(list(x)) == sorted(list(y))

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [95]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max(x[i] for i in range(1, len(x)) if not x[i-1])

5

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [96]:
from itertools import groupby
 
def encode(a):
    return zip(*((key, len(tuple(group))) for key, group in groupby(a)))
 
x = np.array([2, 2, 2, 3, 3, 3, 5])
 
print(tuple(encode(x)))

((2, 3, 5), (3, 3, 1))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [97]:
a = np.array([1,1,1])
b = np.random.rand(20,3)

def euclidean_distances(ref_point, co_ords_array):
    diffs = co_ords_array - ref_point
    sqrd_diffs = np.square(diffs)
    sum_sqrd_diffs = np.sum(sqrd_diffs, axis = 1)
    euc_dists = np.sqrt(sum_sqrd_diffs)
    return euc_dists

euclidean_distances(a, b)

array([0.78883137, 0.76104558, 0.84675494, 0.80582974, 1.20593213,
       1.15936751, 1.08670876, 0.92057516, 0.99553088, 1.09693636,
       0.7289734 , 1.15603158, 0.79101633, 0.86612976, 0.58755248,
       0.97173408, 1.06638188, 1.25013266, 1.17436532, 0.64041681])

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [98]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [99]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [100]:
average_calories = np.average(calorie_stats) - 60
average_calories


46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [101]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [102]:
median_calories = np.median(calorie_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [103]:
nth_percentile = min(np.array([np.percentile(calorie_stats_sorted, x) for x in range(100)]))
nth_percentile

50.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [104]:
more_calories = f'{((len([calorie_stats_sorted[x] for x in range(len(calorie_stats_sorted)) if calorie_stats_sorted[x] > 60]) / len(calorie_stats_sorted)) * 100)}%'
more_calories

'96.1038961038961%'

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [105]:
calorie_std = np.std(calorie_stats_sorted)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [106]:
"""Эти данные могут быть использованы в целях продвижения продукта. Например можно сказать, что в хлопьях CrunchieMunchies меньше каллорий, чем у 96% других производителей."""

'Эти данные могут быть использованы в целях продвижения продукта. Например можно сказать, что в хлопьях CrunchieMunchies меньше каллорий, чем у 96% других производителей.'